# Generated by Django 5.0 on 2023-12-18 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=20)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('experience_required', models.CharField(blank=True, max_length=50, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('application_deadline', models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 16, 20, 49, 32, 643322))),
            ],
        ),
    ]
